apiVersion: azure.database.tanzu.moussaud.org/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: musicstore-pgsql-crossplane
spec:
  location: "france"
  version: "13"
  storageGB: 32
  writeConnectionSecretToRef:
    name: musicstore-pgsql-crossplane-secret
