apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: musicstore-pgsql-operator
spec:
  memory: 800Mi
  cpu: "0.8"
  pgConfig:
    dbname: musicstore-pgsql-operator
    username: pgadmin
    appUser: admin
  imagePullSecret:
    name: app-registry
  highAvailability:
    enabled: false

